---
packages_base:
  amazon_2023: [] # TODO:
  centos_7: [] # TODO:
  debian_13:
    - ca-certificates
    - dbus
    - man
    - openssh-server
    - resolvconf
    - sudo
    - util-linux-extra # porvides: hwclock
