---

- name: Check if running on supported platform
  vars:
    is_amazon_2023: "{{ ansible_distribution == 'Amazon' and ansible_distribution_major_version == '2023' }}"
    is_debian_13: "{{ ansible_distribution == 'Debian' and ansible_distribution_major_version == '13' }}"
  ansible.builtin.assert:
    that:
      # please remember, this is jinja not python
      - is_amazon_2023 or is_debian_13
